name: Yolo Build Dev

on:
  push:
    branches:
     - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
     - uses: actions/checkout@v4
     - name: Build Docker image
       id: build-image
       env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

       run: |
         docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
         
         img_name=${{ secrets.DOCKERHUB_USERNAME }}/yolo-dev:${{github.run_number}}
         img_name1=/yolo-dev:${{github.run_number}}
         
         # same docker_image to pass it to the next workflow 
         echo "image=$img_name1" >> $GITHUB_OUTPUT
          
         # build & push the image 
         docker build --push -t $img_name  .

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy-dev.yaml
    with:
      image: ${{ needs.Build.outputs.image }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_DEV_HOST: ${{ secrets.EC2_DEV_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      AWS_S3_BUCKET_DEV: ${{secrets.AWS_S3_BUCKET_DEV}}