name: Polybot Deploy Dev

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      EC2_DEV_HOST:
        required: true
      EC2_USERNAME:
        required: true
      AWS_S3_BUCKET_DEV:
        required: true
      DETECTION_OBJECTS_DEV:
        required: true
      PREDICTION_SESSIONS_DEV:
        required: true
      SQS_URL_DEV:
        required: true
      POLYBOT_IP_DEV:
        required: true

  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string

env:
  REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_DEV_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          AWS_S3_BUCKET_DEV: ${{secrets.AWS_S3_BUCKET_DEV}}
          DETECTION_OBJECTS_DEV: ${{secrets.DETECTION_OBJECTS_DEV}}
          PREDICTION_SESSIONS_DEV: ${{secrets.PREDICTION_SESSIONS_DEV}}
          SQS_URL_DEV: ${{secrets.SQS_URL_DEV}}
          POLYBOT_IP_DEV: ${{secrets.POLYBOT_IP_DEV}}


        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config << EOF
          Host ec2
              HostName $EC2_HOST
              User $EC2_USERNAME
              IdentityFile ~/.ssh/private_key
              StrictHostKeyChecking no
          EOF

      - name: Execute script on EC2
        run: |
          # Generate .env file. 
          echo "This is the image name :- ${{ inputs.image }}"
          echo "IMG_NAME=mohammadjabaren${{ inputs.image }}" > .env
          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET_DEV }}" >> .env
          echo "STORAGE_TYPE=dynamodb" >> .env
          echo "PREDICTION_SESSIONS=${{ secrets.PREDICTION_SESSIONS_DEV }}" >> .env
          echo "DETECTION_OBJECTS=${{ secrets.DETECTION_OBJECTS_DEV }}" >> .env
          echo "SQS_URL=${{ secrets.SQS_URL_DEV }}" >> .env
          echo "LABEL_GSI=LabelScoreIndex" >> .env
          echo "SCORE_GSI=score_partition-score-index" >> .env
           echo "POLYBOT_IP=${{ secrets.POLYBOT_IP_DEV }}" >> .env
          
          echo "This is the storage type :- $STORAGE_TYPE"
          # Send .env and compose file to EC2
          scp .env docker-compose.dev.yaml otelcol-config.yaml ec2:~/

          # SSH into EC2 and run install + deploy
          ssh ec2 "
            sudo dpkg --configure -a
            sudo apt-get update

            if ! command -v docker &> /dev/null; then
              echo 'Installing Docker...'
              sudo apt-get update
              sudo apt-get install -y ca-certificates curl
              sudo install -m 0755 -d /etc/apt/keyrings
              sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
              sudo chmod a+r /etc/apt/keyrings/docker.asc

              arch=\$(dpkg --print-architecture)
              codename=\$(. /etc/os-release && echo \${UBUNTU_CODENAME:-\$VERSION_CODENAME})
              echo \"deb [arch=\$arch signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \$codename stable\" | \
                sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            else
              echo 'Docker already installed.'
            fi

            if ! command -v docker &> /dev/null; then
              echo 'Docker installation failed or not found. Exiting.'
              exit 1
            fi

            echo 'Starting Docker Compose services...'
            sudo docker compose -f docker-compose.dev.yaml pull
            sudo docker compose -f docker-compose.dev.yaml up -d
          "
        
